name: Update year stats

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "5 0 * * *"
jobs:
  build:
    name: Update-year-stats
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - name: Check out repo
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Clone and run waka-box
        run: |-
          git clone https://github.com/someone120/age-box.git
          cd age-box && go build -o age ./src/main.go
          mv ./age ../ && cd .. && rm -rf age-box/

      - name: Commit and push
        run: |-
          ./age ${secrets.born_year}
          git config --global user.email "bot@github.com" && git config --global user.name "Waka-Bot"
          git add README.md && git commit -m ":memo: update profile" || exit 0
          git pull && git push -f