name: Update wakatime stats

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "5 0 * * *"

jobs:
  build:
    name: Update-waka-stats
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      UPDATE_OPTION: GIST_AND_MARKDOWN
      MARKDOWN_FILE: README.md
      GIST_ID: 8004c9b3b1bd2acd70cbfaaf010f0274
      GIST_BARSTYLE: SOLIDLT
      GIST_BARLENGTH: -1
      GIST_TIMESTYLE: SHORT

    steps:

      - name: Commit and push
        run: |-
          ls
          ./waka
          git config --global user.email "bot@github.com" && git config --global user.name "Waka-Bot"
          git add README.md && git commit -m ":memo: update profile" || exit 0
          git pull && git push -f
          
          
